#!/usr/bin/env python3
"""Regenerate tests/art_fixtures.h — the JPEGs test_art.c decodes.

Needs Pillow (pip install pillow). The header is committed, so the tests
never need Python; this is only for changing the fixtures.
"""
import io
from PIL import Image, ImageDraw

RED, GREEN, BLUE, WHITE = (220, 30, 30), (30, 200, 60), (40, 60, 210), (240, 240, 240)


def quadrants(n):
    im = Image.new("RGB", (n, n))
    d = ImageDraw.Draw(im)
    h = n // 2
    d.rectangle([0, 0, h - 1, h - 1], fill=RED)
    d.rectangle([h, 0, n - 1, h - 1], fill=GREEN)
    d.rectangle([0, h, h - 1, n - 1], fill=BLUE)
    d.rectangle([h, h, n - 1, n - 1], fill=WHITE)
    return im


def thirds(w, h):
    im = Image.new("RGB", (w, h))
    d = ImageDraw.Draw(im)
    t = w // 3
    d.rectangle([0, 0, t - 1, h - 1], fill=RED)
    d.rectangle([t, 0, 2 * t - 1, h - 1], fill=GREEN)
    d.rectangle([2 * t, 0, w - 1, h - 1], fill=BLUE)
    return im


def gray_halves(n):
    im = Image.new("L", (n, n), 40)
    ImageDraw.Draw(im).rectangle([n // 2, 0, n - 1, n - 1], fill=200)
    return im


def first_scan_only(data):
    """Cut a progressive JPEG just after its first scan: the start of the
    second SOS marker. The decoder must never need more than this."""
    i, seen = 2, 0
    while i < len(data) - 4:
        if data[i] != 0xFF:
            i += 1
            continue
        m = data[i + 1]
        if m == 0x00 or m == 0xFF or 0xD0 <= m <= 0xD7:
            i += 2 if m != 0xFF else 1
            continue
        if m == 0xDA:
            seen += 1
            if seen == 2:
                return data[:i + 2]
        if seen == 0:
            i += 2 + ((data[i + 2] << 8) | data[i + 3])
        else:
            i += 2
    return data


def jpeg(im, **kw):
    b = io.BytesIO()
    im.save(b, "JPEG", quality=kw.pop("quality", 92), **kw)
    return b.getvalue()


FIXTURES = [
    ("quad400",  "400x400 quadrants R G / B W, baseline 4:2:0", jpeg(quadrants(400))),
    ("quad64",   "64x64 quadrants, smaller than the art square", jpeg(quadrants(64), subsampling=0)),
    ("wide",     "600x300 thirds R G B, not square: centre-cropped", jpeg(thirds(600, 300))),
    ("gray",     "300x300 greyscale, dark left half, light right half", jpeg(gray_halves(300))),
    ("prog",     "200x200 progressive quadrants, 4:2:0", jpeg(quadrants(200), progressive=True)),
    ("prog1600", "1600x1600 progressive quadrants, cut after the first scan", first_scan_only(jpeg(quadrants(1600), progressive=True, quality=75))),
    ("proggray", "300x300 progressive greyscale halves", jpeg(gray_halves(300), progressive=True)),
    ("progwide", "600x300 progressive thirds, 4:4:4", jpeg(thirds(600, 300), progressive=True, subsampling=0)),
    ("progrst",  "400x400 progressive with restart markers, cut after the first scan", first_scan_only(jpeg(quadrants(400), progressive=True, restart_marker_blocks=3))),
]

with open("tests/art_fixtures.h", "w") as f:
    f.write("/* Generated by tools/mkartfixtures.py — do not edit. */\n")
    f.write("#ifndef ART_FIXTURES_H\n#define ART_FIXTURES_H\n\n#include <stddef.h>\n#include <stdint.h>\n\n")
    for name, what, data in FIXTURES:
        f.write(f"/* {what} ({len(data)} bytes) */\n")
        f.write(f"static const uint8_t FIX_{name.upper()}[] = {{\n")
        for i in range(0, len(data), 16):
            f.write("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",\n")
        f.write("};\n\n")
    f.write("#endif\n")
    for name, what, data in FIXTURES:
        print(f"{name:10s} {len(data):7d} bytes")
