#!/usr/bin/env python3
"""Regenerate tests/art_fixtures.h — the JPEGs test_art.c decodes.

Needs Pillow (pip install pillow). The header is committed, so the tests
never need Python; this is only for changing the fixtures.
"""
import io
from PIL import Image, ImageDraw

RED, GREEN, BLUE, WHITE = (220, 30, 30), (30, 200, 60), (40, 60, 210), (240, 240, 240)


def quadrants(n):
    im = Image.new("RGB", (n, n))
    d = ImageDraw.Draw(im)
    h = n // 2
    d.rectangle([0, 0, h - 1, h - 1], fill=RED)
    d.rectangle([h, 0, n - 1, h - 1], fill=GREEN)
    d.rectangle([0, h, h - 1, n - 1], fill=BLUE)
    d.rectangle([h, h, n - 1, n - 1], fill=WHITE)
    return im


def thirds(w, h):
    im = Image.new("RGB", (w, h))
    d = ImageDraw.Draw(im)
    t = w // 3
    d.rectangle([0, 0, t - 1, h - 1], fill=RED)
    d.rectangle([t, 0, 2 * t - 1, h - 1], fill=GREEN)
    d.rectangle([2 * t, 0, w - 1, h - 1], fill=BLUE)
    return im


def gray_halves(n):
    im = Image.new("L", (n, n), 40)
    ImageDraw.Draw(im).rectangle([n // 2, 0, n - 1, n - 1], fill=200)
    return im


def jpeg(im, **kw):
    b = io.BytesIO()
    im.save(b, "JPEG", quality=kw.pop("quality", 92), **kw)
    return b.getvalue()


FIXTURES = [
    ("quad400",  "400x400 quadrants R G / B W, baseline 4:2:0", jpeg(quadrants(400))),
    ("quad64",   "64x64 quadrants, smaller than the art square", jpeg(quadrants(64), subsampling=0)),
    ("wide",     "600x300 thirds R G B, not square: centre-cropped", jpeg(thirds(600, 300))),
    ("gray",     "300x300 greyscale, dark left half, light right half", jpeg(gray_halves(300))),
    ("prog",     "200x200 progressive — TJpgDec cannot decode these", jpeg(quadrants(200), progressive=True)),
]

with open("tests/art_fixtures.h", "w") as f:
    f.write("/* Generated by tools/mkartfixtures.py — do not edit. */\n")
    f.write("#ifndef ART_FIXTURES_H\n#define ART_FIXTURES_H\n\n#include <stddef.h>\n#include <stdint.h>\n\n")
    for name, what, data in FIXTURES:
        f.write(f"/* {what} ({len(data)} bytes) */\n")
        f.write(f"static const uint8_t FIX_{name.upper()}[] = {{\n")
        for i in range(0, len(data), 16):
            f.write("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",\n")
        f.write("};\n\n")
    f.write("#endif\n")
    for name, what, data in FIXTURES:
        print(f"{name:10s} {len(data):7d} bytes")
